blank_issues_enabled: false
contact_links:
  - name: Contribution Guidelines
    url: https://github.com/ThePhoenix08/open-graph-visualizer/blob/main/.github/CONTRIBUTING.md
    about: Please read the contribution guidelines before creating an issue.
